# Generated by Django 5.0.1 on 2024-01-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home-carusel')),
                ('titlesmall', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=255)),
                ('titlebig', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'carusel',
                'verbose_name_plural': 'carusels',
            },
        ),
    ]
