# Generated by Django 5.0.1 on 2024-01-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincarusel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
