# Generated by Django 5.0.1 on 2024-01-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_myheart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myheart',
            options={'verbose_name': 'Heart', 'verbose_name_plural': 'Hearts'},
        ),
    ]
