# Generated by Django 5.0.1 on 2024-01-31 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_myheart_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myheart',
            options={'verbose_name': 'whishlist', 'verbose_name_plural': 'whishlists'},
        ),
        migrations.AlterUniqueTogether(
            name='myheart',
            unique_together={('user', 'product')},
        ),
    ]
